### ISSUE TITLE
Missing mariadb volume creation

### ISSUE THREAD

**Issue by moorsoft** [major/quadlets-wordpress#1]
The config.butane file in missing the creation of the mariadb.volume

This needs to be added to the config file:
```
storage:
  directories:
    - path: /home/core/.config/containers/systemd/mariadb.volume
      contents:
        inline: |
          [Volume]
      user:
        name: core
      group:
        name: core
```
